ComputerShop/Controllers/MyOrdersController.cs
using ComputerShop.Managers;
using ComputerShop.Models;
using ComputerShop.Validators;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ComputerShop.Controllers
{
    [AuthorizeWithMessage(ErrorMessage = "You must be logged in")]
    public class MyOrdersController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationDbContext db = new ApplicationDbContext();

        public MyOrdersController() { }
        public MyOrdersController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            long UserId = User.Identity.GetUserId<long>();
            Purchase userPurchase = (from p in db.Purchase
                                    where p.UserId == UserId &&
                                    p.IsConfirmed == false
                                    select p).FirstOrDefault();

            return View(userPurchase);

        }
        public async Task<ActionResult> Edit(long? PurchaseId, long? ProductId)
        {
            if (PurchaseId == null || ProductId == null)
            {
                return View("Error");
            }
            long UserId = User.Identity.GetUserId<long>();
            Basket basket = await db.Basket.FindAsync(PurchaseId, ProductId);

            if(basket != null)
            {
                if(basket.Purchase.UserId == UserId)
                {
                    return View(basket);
                }
            }

            return View("Error");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PurchaseId,ProductId,Quantity")]Basket basket)
        {
            long UserId = User.Identity.GetUserId<long>();
            Basket basketExist = await db.Basket.FindAsync(basket.PurchaseId, basket.ProductId);
            if(basketExist != null)
            {
                if (basketExist.Purchase.UserId == UserId)
                {
                    if (ModelState.IsValid)
                    {
                        basketExist.Quantity = basket.Quantity;
                        db.Entry(basketExist).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                    return View(basketExist);
                }
            }
            
            ModelState.AddModelError(string.Empty, "Illegal Operation.");
            return View(basketExist);

        }

        public async Task<ActionResult> Delete(long? PurchaseId, long? ProductId)
        {
            if (PurchaseId == null || ProductId == null)
            {
                return View("Error");
            }
            long UserId = User.Identity.GetUserId<long>();
            Basket basket = await db.Basket.FindAsync(PurchaseId, ProductId);
            if (basket != null)
            {
                if (basket.Purchase.UserId == UserId)
                {
                    return View(basket);
                }
                
            }
            return View("Error");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete([Bind(Include = "PurchaseId,ProductId")]Basket basket)
        {
            long UserId = User.Identity.GetUserId<long>();
            Basket basketUser = await db.Basket.FindAsync(basket.PurchaseId, basket.ProductId);
            if(basketUser != null)
            {
                if (basketUser.Purchase.UserId == UserId)
                {
                    db.Basket.Remove(basketUser);

                    Purchase purchase = await db.Purchase.FindAsync(basket.PurchaseId);
                    if (purchase.Baskets.Count == 0)
                    {
                        db.Purchase.Remove(purchase);
                    }
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
           
            }

            ModelState.AddModelError(string.Empty, "Illegal Operation.");
            return View(basket);
        }
        
    }
}

ComputerShop/Views/MyOrders/Delete.cshtml
@model ComputerShop.Models.Basket

<!DOCTYPE html>

<html>
<head>
	@Styles.Render("~/Content/InputForm.css")
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    	<div class="jumbotron text-center">
    		<h3>Are you sure you want to delete this?</h3>
    
    		<h3>Purchase</h3>
        
    		<table class="table table-bordered">
    			<tbody>
    				
    				<tr>
    					<td>
    						<strong>@Html.DisplayNameFor(model => model.Product.ProductName)</strong>
    					</td>
    					<td>
    						@Html.DisplayFor(model => model.Product.ProductName)
    					</td>
    				</tr>
    				<tr>
    					<td>
    						<strong>@Html.DisplayNameFor(model => model.Product.ProductType)</strong>
    					</td>
    					<td>
    						@Html.DisplayFor(model => model.Product.ProductType)
    					</td>
    				</tr>
    				<tr>
    					<td>
    						<strong>@Html.DisplayNameFor(model => model.Product.Price)</strong>
    					</td>
    					<td>
    						@Html.DisplayFor(model => model.Product.Price)
    					</td>
    				</tr>
    				<tr>
    					<td>
    						<strong>@Html.DisplayNameFor(model => model.Quantity)</strong>
    					</td>
    					<td>
    						@Html.DisplayFor(model => model.Quantity)
    					</td>
    				</tr>
                    <tr>
                        <td>
                            <strong>@Html.DisplayName("price x quantity")</strong>
                        </td>
                        <td>
                            @(Model.Product.Price * Model.Quantity)
                        </td>
                    </tr>
                   
    			</tbody>
    		</table>
    
    		@using (Html.BeginForm("Delete", "MyOrders", FormMethod.Post, new { @class = "form-horizontal" }))
            {
    			@Html.AntiForgeryToken()
                @Html.Hidden("PurchaseId", Model.PurchaseId)
                @Html.Hidden("ProductId", Model.ProductId)

    			<div class="form-actions no-color">
    				<input type="submit" value="Delete" class="btn btn-default" /> |
    				@Html.ActionLink("Back to List", "Index")
    			</div>
    		}
    	</div>
    		
	
</body>
</html>

ComputerShop/Views/MyOrders/Edit.cshtml
@model ComputerShop.Models.Basket

<!DOCTYPE html>

<html>
<head>
    @Styles.Render("~/Content/InputForm.css")
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <div class="jumbotron text-center">

        <h3>Purchase</h3>

        <table class="table table-bordered">
            <tbody>

                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(model => model.Product.ProductName)</strong>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Product.ProductName)
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(model => model.Product.ProductType)</strong>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Product.ProductType)
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(model => model.Product.Price)</strong>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Product.Price)
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>@Html.DisplayNameFor(model => model.Product.ProductionDate)</strong>
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Product.ProductionDate)
                    </td>
                </tr>
            </tbody>
        </table>

        @using (Html.BeginForm("Edit", "MyOrders", FormMethod.Post, new { @class = "form-horizontal" }))
            {
            @Html.AntiForgeryToken()
            @Html.Hidden("PurchaseId", Model.PurchaseId)
            @Html.Hidden("ProductId", Model.ProductId)
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity)
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="Edit" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ComputerShop/Views/MyOrders/Index.cshtml
@using ComputerShop.Models
@model Purchase

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div class="jumbotron text-center">
        @if (Model == null)
        {
            <p>You have not bought any product yet</p>
        }
        else
        {
            <table class="table table-bordered">
                <tr>
                    <th>
                        @Html.DisplayName("Product Name")
                    </th>
                    <th>
                        @Html.DisplayName("Product Type")
                    </th>
                    <th>
                        @Html.DisplayName("Product price")
                    </th>
                    <th>
                        @Html.DisplayName("Quantity")
                    </th>
                    <th>
                        @Html.DisplayName("price x quantity")
                    </th>
                    <th>
                        Edit
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>


                @foreach (Basket b in Model.Baskets)
                {

                    <tr>
                        <th>
                            @b.Product.ProductName
                        </th>
                        <th>
                            @b.Product.ProductType
                        </th>
                        <th>
                            @b.Product.Price
                        </th>
                        <th>
                            @b.Quantity
                        </th>
                        <th>
                            @(b.Product.Price * b.Quantity)
                        </th>
                        <th>
                            @Html.ActionLink("[ Edit ]", "Edit", routeValues: new { PurchaseId = Model.Id, ProductId = b.ProductId })
                            
                        </th>
                        <th>
                            @Html.ActionLink("[ Delete ]", "Delete", routeValues: new { PurchaseId = Model.Id, ProductId = b.ProductId})
                        </th>
                    </tr>
                }
            </table>
            <hr />
            <p class="text-right">Sum: @Model.SumToPay</p>

        }
            


    </div>

    </body>
</html>